// Comprehensive list of Chennai areas compiled from 99acres, nobroker, magicbricks
// Sorted alphabetically for easy lookup

export const CHENNAI_AREAS: string[] = [
    'Adambakkam',
    'Adyar',
    'Alandur',
    'Alwarpet',
    'Ambattur',
    'Aminjikarai',
    'Anna Nagar',
    'Anna Nagar East',
    'Anna Nagar West',
    'Annanur',
    'Ashok Nagar',
    'Avadi',
    'Ayanambakkam',
    'Besant Nagar',
    'Chromepet',
    'Choolaimedu',
    'Chetpet',
    'ECR',
    'Egmore',
    'Ekkaduthangal',
    'Ennore',
    'Gerugambakkam',
    'Guindy',
    'GST Road',
    'Guduvancheri',
    'OMR',
    'Iyyappanthangal',
    'Jafferkhanpet',
    'K.K. Nagar',
    'Kadapperi',
    'Karapakkam',
    'Kattupakkam',
    'Keelkattalai',
    'Kelambakkam',
    'Kilpauk',
    'Kodambakkam',
    'Kodungaiyur',
    'Kolathur',
    'Korattur',
    'Kottivakkam',
    'Kovur',
    'Koyambedu',
    'Kundrathur',
    'Madambakkam',
    'Madhavaram',
    'Madipakkam',
    'Maduravoyal',
    'Manapakkam',
    'Mandaveli',
    'Mangadu',
    'Mannivakkam',
    'Manali',
    'Mappedu',
    'Medavakkam',
    'Meenambakkam',
    'Mogappair',
    'Mogappair East',
    'Mogappair West',
    'Moulivakkam',
    'Mugalivakkam',
    'Mylapore',
    'Nanganallur',
    'Navalur',
    'Neelankarai',
    'Nungambakkam',
    'Old Washermanpet',
    'Oragadam',
    'Padappai',
    'Padur',
    'Pallavaram',
    'Pallikaranai',
    'Pammal',
    'Pattabiram',
    'Pazhavanthangal',
    'Perambur',
    'Perumbakkam',
    'Perungalathur',
    'Perungudi',
    'Poonamallee',
    'Porur',
    'Purasawalkam',
    'R.A. Puram',
    'Ramapuram',
    'Royapettah',
    'Royapuram',
    'Saidapet',
    'Selaiyur',
    'Shenoy Nagar',
    'Sholinganallur',
    'Siruseri',
    'Sithalapakkam',
    'Sriperumbudur',
    'St. Thomas Mount',
    'T. Nagar',
    'Tambaram',
    'Tambaram East',
    'Tambaram West',
    'Teynampet',
    'Tharamani',
    'Thirumazhisai',
    'Thirumudivakkam',
    'Thiruneermalai',
    'Thiruporur',
    'Thiruvanmiyur',
    'Thoraipakkam',
    'Tiruvallur',
    'Tiruvottiyur',
    'Tondiarpet',
    'Urapakkam',
    'Vadapalani',
    'Valasaravakkam',
    'Vanagaram',
    'Vandalur',
    'Velachery',
    'Villivakkam',
    'Virugambakkam',
    'Washermanpet',
    'West Mambalam',
    'Palavakkam',
    'Injambakkam',
    'Mambakkam',
    'Mahindra World City',
    'Nemam',
    'Pozhichalur',
    'Manimangalam',
    'Paruthipattu',
].sort();
